version: "3.9"
services:
  app:
    build:
      dockerfile: 'docker/Dockerfile'
      context: '..'
      target: dev
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - '..:/app'
    environment:
      NODE_ENV: development

  mongodb:
    image: mongo:5.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

networks:
  app:
    driver: bridge